[package]
name = "amm"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.partisiablockchain]
cargo-partisia = "0.2.9"

[dependencies]


byoc = { path = "../../packages/byoc", features = ["abi"] } 

